# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainedited.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QCheckBox,
    QComboBox, QFrame, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QTabWidget, QTableWidget, QTableWidgetItem,
    QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1680, 1050)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(1920, 1080))
        font = QFont()
        font.setPointSize(22)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1680, 1050))
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.login = QWidget()
        self.login.setObjectName(u"login")
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.btn_qr = QPushButton(self.login)
        self.btn_qr.setObjectName(u"btn_qr")
        self.btn_qr.setGeometry(QRect(1102, 291, 480, 480))
        self.btn_qr.setFocusPolicy(Qt.NoFocus)
        icon = QIcon()
        icon.addFile(u"QRcode.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_qr.setIcon(icon)
        self.btn_qr.setIconSize(QSize(480, 480))
        self.btn_login = QPushButton(self.login)
        self.btn_login.setObjectName(u"btn_login")
        self.btn_login.setGeometry(QRect(490, 700, 350, 115))
        font1 = QFont()
        font1.setPointSize(60)
        self.btn_login.setFont(font1)
        self.btn_login.setFocusPolicy(Qt.StrongFocus)
        self.btn_login.setAutoDefault(False)
        self.line_stdnr = QLineEdit(self.login)
        self.line_stdnr.setObjectName(u"line_stdnr")
        self.line_stdnr.setGeometry(QRect(105, 230, 735, 115))
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.line_stdnr.sizePolicy().hasHeightForWidth())
        self.line_stdnr.setSizePolicy(sizePolicy1)
        font2 = QFont()
        font2.setPointSize(50)
        self.line_stdnr.setFont(font2)
        self.line_stdnr.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhPreferNumbers|Qt.ImhSensitiveData)
        self.line_stdnr.setFrame(False)
        self.line_stdnr.setEchoMode(QLineEdit.Normal)
        self.line_stdnr.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.line_pswrd = QLineEdit(self.login)
        self.line_pswrd.setObjectName(u"line_pswrd")
        self.line_pswrd.setGeometry(QRect(105, 465, 735, 115))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.line_pswrd.sizePolicy().hasHeightForWidth())
        self.line_pswrd.setSizePolicy(sizePolicy2)
        self.line_pswrd.setFont(font2)
        self.line_pswrd.setFocusPolicy(Qt.StrongFocus)
        self.line_pswrd.setFrame(False)
        self.line_pswrd.setEchoMode(QLineEdit.Password)
        self.line_pswrd.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.line_pswrd.setClearButtonEnabled(False)
        self.line_qr = QLineEdit(self.login)
        self.line_qr.setObjectName(u"line_qr")
        self.line_qr.setGeometry(QRect(-200, 0, 50, 50))
        self.line_qr.setCursor(QCursor(Qt.BlankCursor))
        self.line_qr.setFocusPolicy(Qt.ClickFocus)
        self.line_qr.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.line_qr.setMaxLength(500000)
        self.line_qr.setFrame(False)
        self.line_qr.setEchoMode(QLineEdit.NoEcho)
        self.ERROR_STDNR = QLabel(self.login)
        self.ERROR_STDNR.setObjectName(u"ERROR_STDNR")
        self.ERROR_STDNR.setGeometry(QRect(105, 384, 735, 50))
        self.ERROR_PSWRD = QLabel(self.login)
        self.ERROR_PSWRD.setObjectName(u"ERROR_PSWRD")
        self.ERROR_PSWRD.setGeometry(QRect(105, 600, 735, 75))
        self.ERROR_QRFLD = QLabel(self.login)
        self.ERROR_QRFLD.setObjectName(u"ERROR_QRFLD")
        self.ERROR_QRFLD.setGeometry(QRect(1128, 792, 367, 50))
        self.btn_retpass = QPushButton(self.login)
        self.btn_retpass.setObjectName(u"btn_retpass")
        self.btn_retpass.setGeometry(QRect(105, 700, 350, 115))
        font3 = QFont()
        font3.setPointSize(25)
        self.btn_retpass.setFont(font3)
        self.btn_retpass.setFocusPolicy(Qt.NoFocus)
        self.btn_retpass.setAutoDefault(False)
        self.stackedWidget.addWidget(self.login)
        self.main = QWidget()
        self.main.setObjectName(u"main")
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.buy_btn = QPushButton(self.main)
        self.buy_btn.setObjectName(u"buy_btn")
        self.buy_btn.setGeometry(QRect(0, 0, 420, 175))
        self.buy_btn.setFont(font)
        self.buy_btn.setFocusPolicy(Qt.NoFocus)
        self.buy_btn.setCheckable(True)
        self.buy_btn.setChecked(True)
        self.buy_btn.setAutoExclusive(True)
        self.stat_btn = QPushButton(self.main)
        self.stat_btn.setObjectName(u"stat_btn")
        self.stat_btn.setGeometry(QRect(0, 175, 420, 175))
        self.stat_btn.setFont(font)
        self.stat_btn.setFocusPolicy(Qt.NoFocus)
        self.stat_btn.setCheckable(True)
        self.stat_btn.setChecked(False)
        self.stat_btn.setAutoExclusive(True)
        self.prof_btn = QPushButton(self.main)
        self.prof_btn.setObjectName(u"prof_btn")
        self.prof_btn.setGeometry(QRect(0, 350, 420, 175))
        self.prof_btn.setFont(font)
        self.prof_btn.setFocusPolicy(Qt.NoFocus)
        self.prof_btn.setCheckable(True)
        self.prof_btn.setChecked(False)
        self.prof_btn.setAutoExclusive(True)
        self.prod_btn = QPushButton(self.main)
        self.prod_btn.setObjectName(u"prod_btn")
        self.prod_btn.setEnabled(True)
        self.prod_btn.setGeometry(QRect(0, 525, 420, 175))
        self.prod_btn.setFont(font)
        self.prod_btn.setFocusPolicy(Qt.NoFocus)
        self.prod_btn.setCheckable(True)
        self.prod_btn.setChecked(False)
        self.prod_btn.setAutoExclusive(True)
        self.user_btn = QPushButton(self.main)
        self.user_btn.setObjectName(u"user_btn")
        self.user_btn.setGeometry(QRect(0, 700, 420, 175))
        self.user_btn.setFont(font)
        self.user_btn.setFocusPolicy(Qt.NoFocus)
        self.user_btn.setCheckable(True)
        self.user_btn.setChecked(False)
        self.user_btn.setAutoExclusive(True)
        self.logout_btn = QPushButton(self.main)
        self.logout_btn.setObjectName(u"logout_btn")
        self.logout_btn.setGeometry(QRect(0, 875, 420, 175))
        self.logout_btn.setFont(font)
        self.logout_btn.setFocusPolicy(Qt.NoFocus)
        self.logout_btn.setCheckable(False)
        self.logout_btn.setChecked(False)
        self.logout_btn.setAutoExclusive(False)
        self.pages = QStackedWidget(self.main)
        self.pages.setObjectName(u"pages")
        self.pages.setGeometry(QRect(420, 0, 1260, 1050))
        self.pages.setFrameShape(QFrame.Box)
        self.pages.setFrameShadow(QFrame.Plain)
        self.pages.setLineWidth(0)
        self.buy_page = QWidget()
        self.buy_page.setObjectName(u"buy_page")
        self.pay_btn = QPushButton(self.buy_page)
        self.pay_btn.setObjectName(u"pay_btn")
        self.pay_btn.setGeometry(QRect(840, 875, 420, 175))
        self.pay_btn.setFont(font)
        self.pay_btn.setFocusPolicy(Qt.NoFocus)
        self.cart_fld = QTableWidget(self.buy_page)
        if (self.cart_fld.columnCount() < 5):
            self.cart_fld.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.cart_fld.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem1.setFont(font);
        self.cart_fld.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font);
        self.cart_fld.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setFont(font);
        self.cart_fld.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setFont(font);
        self.cart_fld.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.cart_fld.setObjectName(u"cart_fld")
        self.cart_fld.setGeometry(QRect(0, 0, 1260, 875))
        font4 = QFont()
        font4.setPointSize(18)
        self.cart_fld.setFont(font4)
        self.cart_fld.setFocusPolicy(Qt.NoFocus)
        self.cart_fld.setFrameShape(QFrame.Box)
        self.cart_fld.setFrameShadow(QFrame.Plain)
        self.cart_fld.setLineWidth(0)
        self.cart_fld.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.cart_fld.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.cart_fld.setAutoScroll(False)
        self.cart_fld.setSelectionMode(QAbstractItemView.SingleSelection)
        self.cart_fld.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.cart_fld.setShowGrid(True)
        self.cart_fld.setRowCount(0)
        self.cart_fld.setColumnCount(5)
        self.cart_fld.horizontalHeader().setDefaultSectionSize(100)
        self.cart_fld.horizontalHeader().setStretchLastSection(False)
        self.cart_fld.verticalHeader().setVisible(False)
        self.cart_fld.verticalHeader().setStretchLastSection(False)
        self.gebruiker_lbl = QLabel(self.buy_page)
        self.gebruiker_lbl.setObjectName(u"gebruiker_lbl")
        self.gebruiker_lbl.setGeometry(QRect(10, 875, 140, 50))
        self.gebruiker_lbl.setFont(font)
        self.gebruiker_lbl.setTextFormat(Qt.RichText)
        self.gebruiker_lbl.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.teGoed_lbl = QLabel(self.buy_page)
        self.teGoed_lbl.setObjectName(u"teGoed_lbl")
        self.teGoed_lbl.setGeometry(QRect(10, 925, 140, 50))
        self.teGoed_lbl.setFont(font)
        self.teGoed_lbl.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.gebruiker_fld = QLabel(self.buy_page)
        self.gebruiker_fld.setObjectName(u"gebruiker_fld")
        self.gebruiker_fld.setGeometry(QRect(150, 875, 130, 50))
        self.gebruiker_fld.setFont(font)
        self.gebruiker_fld.setTextFormat(Qt.RichText)
        self.gebruiker_fld.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.euroteken = QLabel(self.buy_page)
        self.euroteken.setObjectName(u"euroteken")
        self.euroteken.setGeometry(QRect(150, 925, 20, 50))
        self.euroteken.setFont(font)
        self.euroteken.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.teGoed_fld = QLabel(self.buy_page)
        self.teGoed_fld.setObjectName(u"teGoed_fld")
        self.teGoed_fld.setGeometry(QRect(170, 925, 110, 50))
        self.teGoed_fld.setFont(font)
        self.teGoed_fld.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.item_fld = QLineEdit(self.buy_page)
        self.item_fld.setObjectName(u"item_fld")
        self.item_fld.setGeometry(QRect(0, -10, 1, 1))
        self.euroteken_2 = QLabel(self.buy_page)
        self.euroteken_2.setObjectName(u"euroteken_2")
        self.euroteken_2.setGeometry(QRect(705, 925, 20, 50))
        self.euroteken_2.setFont(font)
        self.euroteken_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.totaal_lbl = QLabel(self.buy_page)
        self.totaal_lbl.setObjectName(u"totaal_lbl")
        self.totaal_lbl.setGeometry(QRect(705, 875, 130, 50))
        self.totaal_lbl.setFont(font)
        self.totaal_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.totaal_fld = QLabel(self.buy_page)
        self.totaal_fld.setObjectName(u"totaal_fld")
        self.totaal_fld.setGeometry(QRect(725, 925, 110, 50))
        self.totaal_fld.setFont(font)
        self.totaal_fld.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.ERROR_ITMFLD = QLabel(self.buy_page)
        self.ERROR_ITMFLD.setObjectName(u"ERROR_ITMFLD")
        self.ERROR_ITMFLD.setGeometry(QRect(262, 875, 445, 50))
        self.pages.addWidget(self.buy_page)
        self.stat_page = QWidget()
        self.stat_page.setObjectName(u"stat_page")
        self.stat_widget = QWidget(self.stat_page)
        self.stat_widget.setObjectName(u"stat_widget")
        self.stat_widget.setGeometry(QRect(40, 20, 1180, 875))
        self.lbl_spend = QLabel(self.stat_page)
        self.lbl_spend.setObjectName(u"lbl_spend")
        self.lbl_spend.setGeometry(QRect(40, 950, 240, 50))
        self.lbl_spend.setFont(font)
        self.lbl_bought = QLabel(self.stat_page)
        self.lbl_bought.setObjectName(u"lbl_bought")
        self.lbl_bought.setGeometry(QRect(640, 950, 360, 50))
        self.lbl_bought.setFont(font)
        self.euroteken_8 = QLabel(self.stat_page)
        self.euroteken_8.setObjectName(u"euroteken_8")
        self.euroteken_8.setGeometry(QRect(280, 950, 20, 50))
        self.euroteken_8.setFont(font)
        self.euroteken_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.fld_spend = QLabel(self.stat_page)
        self.fld_spend.setObjectName(u"fld_spend")
        self.fld_spend.setGeometry(QRect(300, 950, 225, 50))
        self.fld_spend.setFont(font)
        self.fld_bought = QLabel(self.stat_page)
        self.fld_bought.setObjectName(u"fld_bought")
        self.fld_bought.setGeometry(QRect(1000, 950, 220, 50))
        self.fld_bought.setFont(font)
        self.pages.addWidget(self.stat_page)
        self.prof_page = QWidget()
        self.prof_page.setObjectName(u"prof_page")
        self.prof_page.setToolTipDuration(10)
        self.line_BLOCK_prof = QCheckBox(self.prof_page)
        self.line_BLOCK_prof.setObjectName(u"line_BLOCK_prof")
        self.line_BLOCK_prof.setGeometry(QRect(550, 650, 500, 40))
        self.line_BLOCK_prof.setFont(font)
        self.line_BLOCK_prof.setFocusPolicy(Qt.NoFocus)
        self.line_BLOCK_prof.setContextMenuPolicy(Qt.NoContextMenu)
        self.line_BLOCK_prof.setCheckable(False)
        self.line_NAME_prof = QLineEdit(self.prof_page)
        self.line_NAME_prof.setObjectName(u"line_NAME_prof")
        self.line_NAME_prof.setGeometry(QRect(550, 190, 500, 40))
        self.line_NAME_prof.setFont(font)
        self.line_NAME_prof.setFrame(False)
        self.lbl_AMOUNT_prof = QLabel(self.prof_page)
        self.lbl_AMOUNT_prof.setObjectName(u"lbl_AMOUNT_prof")
        self.lbl_AMOUNT_prof.setGeometry(QRect(185, 420, 215, 40))
        self.lbl_AMOUNT_prof.setFont(font)
        self.lbl_BLOCK_prof = QLabel(self.prof_page)
        self.lbl_BLOCK_prof.setObjectName(u"lbl_BLOCK_prof")
        self.lbl_BLOCK_prof.setGeometry(QRect(185, 650, 215, 40))
        self.lbl_BLOCK_prof.setFont(font)
        self.euroteken_prof = QLabel(self.prof_page)
        self.euroteken_prof.setObjectName(u"euroteken_prof")
        self.euroteken_prof.setGeometry(QRect(550, 420, 20, 40))
        self.euroteken_prof.setFont(font)
        self.euroteken_prof.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_PASSWORD_prof = QLineEdit(self.prof_page)
        self.line_PASSWORD_prof.setObjectName(u"line_PASSWORD_prof")
        self.line_PASSWORD_prof.setGeometry(QRect(550, 535, 500, 40))
        self.line_PASSWORD_prof.setFont(font)
        self.line_PASSWORD_prof.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.line_PASSWORD_prof.setFrame(False)
        self.line_PASSWORD_prof.setEchoMode(QLineEdit.Password)
        self.line_ID_prof = QLineEdit(self.prof_page)
        self.line_ID_prof.setObjectName(u"line_ID_prof")
        self.line_ID_prof.setGeometry(QRect(550, 75, 500, 40))
        self.line_ID_prof.setFont(font)
        self.line_ID_prof.setFocusPolicy(Qt.NoFocus)
        self.line_ID_prof.setFrame(False)
        self.ERROR_UPDUSR_prof = QLabel(self.prof_page)
        self.ERROR_UPDUSR_prof.setObjectName(u"ERROR_UPDUSR_prof")
        self.ERROR_UPDUSR_prof.setGeometry(QRect(157, 930, 525, 60))
        self.ERROR_UPDUSR_prof.setFont(font)
        self.lbl_TITLE_prof = QLabel(self.prof_page)
        self.lbl_TITLE_prof.setObjectName(u"lbl_TITLE_prof")
        self.lbl_TITLE_prof.setGeometry(QRect(185, 305, 215, 40))
        self.lbl_TITLE_prof.setFont(font)
        self.lbl_ID_prof = QLabel(self.prof_page)
        self.lbl_ID_prof.setObjectName(u"lbl_ID_prof")
        self.lbl_ID_prof.setGeometry(QRect(185, 75, 215, 40))
        self.lbl_ID_prof.setFont(font)
        self.lbl_NAME_prof = QLabel(self.prof_page)
        self.lbl_NAME_prof.setObjectName(u"lbl_NAME_prof")
        self.lbl_NAME_prof.setGeometry(QRect(185, 190, 215, 40))
        self.lbl_NAME_prof.setFont(font)
        self.lbl_PASSWORD_prof = QLabel(self.prof_page)
        self.lbl_PASSWORD_prof.setObjectName(u"lbl_PASSWORD_prof")
        self.lbl_PASSWORD_prof.setGeometry(QRect(185, 535, 215, 40))
        self.lbl_PASSWORD_prof.setFont(font)
        self.btn_EDIT_prof = QPushButton(self.prof_page)
        self.btn_EDIT_prof.setObjectName(u"btn_EDIT_prof")
        self.btn_EDIT_prof.setGeometry(QRect(840, 875, 420, 175))
        self.btn_EDIT_prof.setFont(font)
        self.btn_EDIT_prof.setFocusPolicy(Qt.NoFocus)
        self.btn_EDIT_prof.setCheckable(False)
        self.btn_EDIT_prof.setChecked(False)
        self.btn_EDIT_prof.setAutoExclusive(False)
        self.lbl_QR_prof = QLabel(self.prof_page)
        self.lbl_QR_prof.setObjectName(u"lbl_QR_prof")
        self.lbl_QR_prof.setGeometry(QRect(185, 765, 215, 40))
        self.lbl_QR_prof.setFont(font)
        self.line_AMOUNT_prof = QLineEdit(self.prof_page)
        self.line_AMOUNT_prof.setObjectName(u"line_AMOUNT_prof")
        self.line_AMOUNT_prof.setGeometry(QRect(570, 420, 480, 40))
        self.line_AMOUNT_prof.setFont(font)
        self.line_AMOUNT_prof.setFocusPolicy(Qt.NoFocus)
        self.line_AMOUNT_prof.setFrame(False)
        self.line_QR_prof = QLineEdit(self.prof_page)
        self.line_QR_prof.setObjectName(u"line_QR_prof")
        self.line_QR_prof.setGeometry(QRect(550, 765, 500, 40))
        self.line_QR_prof.setFont(font)
        self.line_QR_prof.setFrame(False)
        self.line_TITLE_prof = QLineEdit(self.prof_page)
        self.line_TITLE_prof.setObjectName(u"line_TITLE_prof")
        self.line_TITLE_prof.setGeometry(QRect(550, 305, 500, 40))
        self.line_TITLE_prof.setFont(font)
        self.line_TITLE_prof.setFocusPolicy(Qt.NoFocus)
        self.line_TITLE_prof.setInputMethodHints(Qt.ImhNone)
        self.line_TITLE_prof.setFrame(False)
        self.line_TITLE_prof.setEchoMode(QLineEdit.Normal)
        self.pages.addWidget(self.prof_page)
        self.prod_page = QWidget()
        self.prod_page.setObjectName(u"prod_page")
        self.EditProd_btn = QPushButton(self.prod_page)
        self.EditProd_btn.setObjectName(u"EditProd_btn")
        self.EditProd_btn.setGeometry(QRect(700, 875, 420, 175))
        self.EditProd_btn.setFont(font)
        self.EditProd_btn.setFocusPolicy(Qt.NoFocus)
        self.NewProd_btn = QPushButton(self.prod_page)
        self.NewProd_btn.setObjectName(u"NewProd_btn")
        self.NewProd_btn.setGeometry(QRect(140, 875, 420, 175))
        self.NewProd_btn.setFont(font)
        self.NewProd_btn.setFocusPolicy(Qt.NoFocus)
        self.ProdList = QTableWidget(self.prod_page)
        if (self.ProdList.columnCount() < 7):
            self.ProdList.setColumnCount(7)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setFont(font);
        self.ProdList.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        __qtablewidgetitem6.setFont(font);
        self.ProdList.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font);
        self.ProdList.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font);
        self.ProdList.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setFont(font);
        self.ProdList.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setFont(font);
        self.ProdList.setHorizontalHeaderItem(5, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.ProdList.setHorizontalHeaderItem(6, __qtablewidgetitem11)
        self.ProdList.setObjectName(u"ProdList")
        self.ProdList.setGeometry(QRect(0, 0, 1260, 875))
        self.ProdList.setFont(font4)
        self.ProdList.setFrameShape(QFrame.NoFrame)
        self.ProdList.setFrameShadow(QFrame.Sunken)
        self.ProdList.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ProdList.setAlternatingRowColors(False)
        self.ProdList.setSelectionMode(QAbstractItemView.SingleSelection)
        self.ProdList.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.ProdList.horizontalHeader().setDefaultSectionSize(100)
        self.ProdList.horizontalHeader().setProperty("showSortIndicator", True)
        self.ProdList.verticalHeader().setVisible(False)
        self.pages.addWidget(self.prod_page)
        self.user_page = QWidget()
        self.user_page.setObjectName(u"user_page")
        self.Users = QStackedWidget(self.user_page)
        self.Users.setObjectName(u"Users")
        self.Users.setGeometry(QRect(0, 0, 1260, 1050))
        self.UserMenu_page = QWidget()
        self.UserMenu_page.setObjectName(u"UserMenu_page")
        self.UpdateUser_btn = QPushButton(self.UserMenu_page)
        self.UpdateUser_btn.setObjectName(u"UpdateUser_btn")
        self.UpdateUser_btn.setGeometry(QRect(420, 130, 420, 180))
        self.UpdateUser_btn.setFont(font)
        self.UpdateUser_btn.setFocusPolicy(Qt.NoFocus)
        self.EditUser_btn = QPushButton(self.UserMenu_page)
        self.EditUser_btn.setObjectName(u"EditUser_btn")
        self.EditUser_btn.setGeometry(QRect(420, 435, 420, 180))
        self.EditUser_btn.setFont(font)
        self.EditUser_btn.setFocusPolicy(Qt.NoFocus)
        self.NewUser_btn = QPushButton(self.UserMenu_page)
        self.NewUser_btn.setObjectName(u"NewUser_btn")
        self.NewUser_btn.setGeometry(QRect(420, 740, 420, 180))
        self.NewUser_btn.setFont(font)
        self.NewUser_btn.setFocusPolicy(Qt.NoFocus)
        self.Users.addWidget(self.UserMenu_page)
        self.NewUser_page = QWidget()
        self.NewUser_page.setObjectName(u"NewUser_page")
        self.lbl_ID_ADD = QLabel(self.NewUser_page)
        self.lbl_ID_ADD.setObjectName(u"lbl_ID_ADD")
        self.lbl_ID_ADD.setGeometry(QRect(185, 75, 220, 40))
        self.lbl_ID_ADD.setFont(font)
        self.line_AMOUNT_ADD = QLineEdit(self.NewUser_page)
        self.line_AMOUNT_ADD.setObjectName(u"line_AMOUNT_ADD")
        self.line_AMOUNT_ADD.setGeometry(QRect(570, 420, 480, 40))
        self.line_AMOUNT_ADD.setFont(font)
        self.line_AMOUNT_ADD.setFrame(False)
        self.line_PASSWORD_ADD = QLineEdit(self.NewUser_page)
        self.line_PASSWORD_ADD.setObjectName(u"line_PASSWORD_ADD")
        self.line_PASSWORD_ADD.setGeometry(QRect(550, 535, 500, 40))
        self.line_PASSWORD_ADD.setFont(font)
        self.line_PASSWORD_ADD.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.line_PASSWORD_ADD.setFrame(False)
        self.line_PASSWORD_ADD.setEchoMode(QLineEdit.Password)
        self.lbl_TITLE_ADD = QLabel(self.NewUser_page)
        self.lbl_TITLE_ADD.setObjectName(u"lbl_TITLE_ADD")
        self.lbl_TITLE_ADD.setGeometry(QRect(185, 305, 220, 40))
        self.lbl_TITLE_ADD.setFont(font)
        self.lbl_BLOCK_ADD = QLabel(self.NewUser_page)
        self.lbl_BLOCK_ADD.setObjectName(u"lbl_BLOCK_ADD")
        self.lbl_BLOCK_ADD.setGeometry(QRect(185, 650, 220, 40))
        self.lbl_BLOCK_ADD.setFont(font)
        self.lbl_QR_ADD = QLabel(self.NewUser_page)
        self.lbl_QR_ADD.setObjectName(u"lbl_QR_ADD")
        self.lbl_QR_ADD.setGeometry(QRect(185, 765, 220, 40))
        self.lbl_QR_ADD.setFont(font)
        self.line_TITLE_ADD = QComboBox(self.NewUser_page)
        self.line_TITLE_ADD.addItem("")
        self.line_TITLE_ADD.addItem("")
        self.line_TITLE_ADD.addItem("")
        self.line_TITLE_ADD.setObjectName(u"line_TITLE_ADD")
        self.line_TITLE_ADD.setGeometry(QRect(550, 305, 500, 40))
        self.line_TITLE_ADD.setFont(font)
        self.line_TITLE_ADD.setFrame(False)
        self.lbl_PASSWORD_ADD = QLabel(self.NewUser_page)
        self.lbl_PASSWORD_ADD.setObjectName(u"lbl_PASSWORD_ADD")
        self.lbl_PASSWORD_ADD.setGeometry(QRect(185, 535, 220, 40))
        self.lbl_PASSWORD_ADD.setFont(font)
        self.btn_ADD = QPushButton(self.NewUser_page)
        self.btn_ADD.setObjectName(u"btn_ADD")
        self.btn_ADD.setGeometry(QRect(840, 875, 420, 175))
        self.btn_ADD.setFont(font)
        self.btn_ADD.setFocusPolicy(Qt.NoFocus)
        self.btn_ADD.setCheckable(False)
        self.btn_ADD.setChecked(False)
        self.btn_ADD.setAutoExclusive(False)
        self.lbl_NAME_ADD = QLabel(self.NewUser_page)
        self.lbl_NAME_ADD.setObjectName(u"lbl_NAME_ADD")
        self.lbl_NAME_ADD.setGeometry(QRect(185, 190, 220, 40))
        self.lbl_NAME_ADD.setFont(font)
        self.lbl_AMOUNT_ADD = QLabel(self.NewUser_page)
        self.lbl_AMOUNT_ADD.setObjectName(u"lbl_AMOUNT_ADD")
        self.lbl_AMOUNT_ADD.setGeometry(QRect(185, 420, 220, 40))
        self.lbl_AMOUNT_ADD.setFont(font)
        self.line_QR_ADD = QLineEdit(self.NewUser_page)
        self.line_QR_ADD.setObjectName(u"line_QR_ADD")
        self.line_QR_ADD.setGeometry(QRect(550, 765, 500, 40))
        self.line_QR_ADD.setFont(font)
        self.line_QR_ADD.setFrame(False)
        self.line_BLOCK_ADD = QCheckBox(self.NewUser_page)
        self.line_BLOCK_ADD.setObjectName(u"line_BLOCK_ADD")
        self.line_BLOCK_ADD.setGeometry(QRect(550, 650, 500, 40))
        font5 = QFont()
        font5.setPointSize(23)
        self.line_BLOCK_ADD.setFont(font5)
        self.line_ID_ADD = QLineEdit(self.NewUser_page)
        self.line_ID_ADD.setObjectName(u"line_ID_ADD")
        self.line_ID_ADD.setGeometry(QRect(550, 75, 500, 40))
        self.line_ID_ADD.setFont(font)
        self.line_ID_ADD.setFrame(False)
        self.line_NAME_ADD = QLineEdit(self.NewUser_page)
        self.line_NAME_ADD.setObjectName(u"line_NAME_ADD")
        self.line_NAME_ADD.setGeometry(QRect(550, 190, 500, 40))
        self.line_NAME_ADD.setFont(font)
        self.line_NAME_ADD.setFrame(False)
        self.euroteken_4 = QLabel(self.NewUser_page)
        self.euroteken_4.setObjectName(u"euroteken_4")
        self.euroteken_4.setGeometry(QRect(550, 420, 20, 40))
        self.euroteken_4.setFont(font)
        self.euroteken_4.setStyleSheet(u"")
        self.euroteken_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.ERROR_ADDUSR = QLabel(self.NewUser_page)
        self.ERROR_ADDUSR.setObjectName(u"ERROR_ADDUSR")
        self.ERROR_ADDUSR.setGeometry(QRect(157, 930, 525, 60))
        self.ERROR_ADDUSR.setFont(font)
        self.Users.addWidget(self.NewUser_page)
        self.UpdateUser_page = QWidget()
        self.UpdateUser_page.setObjectName(u"UpdateUser_page")
        self.INC_lbl_ID = QLabel(self.UpdateUser_page)
        self.INC_lbl_ID.setObjectName(u"INC_lbl_ID")
        self.INC_lbl_ID.setGeometry(QRect(250, 150, 250, 40))
        self.INC_lbl_ID.setFont(font)
        self.INC_line_ID = QLineEdit(self.UpdateUser_page)
        self.INC_line_ID.setObjectName(u"INC_line_ID")
        self.INC_line_ID.setGeometry(QRect(510, 148, 500, 40))
        self.INC_line_ID.setFont(font)
        self.INC_line_ID.setFrame(False)
        self.INC_lbl_AMOUNT = QLabel(self.UpdateUser_page)
        self.INC_lbl_AMOUNT.setObjectName(u"INC_lbl_AMOUNT")
        self.INC_lbl_AMOUNT.setGeometry(QRect(250, 336, 250, 40))
        self.INC_lbl_AMOUNT.setFont(font)
        self.INC_line_AMOUNT = QLabel(self.UpdateUser_page)
        self.INC_line_AMOUNT.setObjectName(u"INC_line_AMOUNT")
        self.INC_line_AMOUNT.setGeometry(QRect(530, 336, 480, 40))
        self.INC_line_AMOUNT.setFont(font)
        self.euroteken_3 = QLabel(self.UpdateUser_page)
        self.euroteken_3.setObjectName(u"euroteken_3")
        self.euroteken_3.setGeometry(QRect(510, 336, 20, 40))
        self.euroteken_3.setFont(font)
        self.euroteken_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.euroteken_6 = QLabel(self.UpdateUser_page)
        self.euroteken_6.setObjectName(u"euroteken_6")
        self.euroteken_6.setGeometry(QRect(510, 524, 20, 40))
        self.euroteken_6.setFont(font)
        self.euroteken_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.INC_lbl_INC = QLabel(self.UpdateUser_page)
        self.INC_lbl_INC.setObjectName(u"INC_lbl_INC")
        self.INC_lbl_INC.setGeometry(QRect(250, 524, 250, 40))
        self.INC_lbl_INC.setFont(font)
        self.INC_line_INC = QLineEdit(self.UpdateUser_page)
        self.INC_line_INC.setObjectName(u"INC_line_INC")
        self.INC_line_INC.setGeometry(QRect(530, 524, 480, 40))
        self.INC_line_INC.setFont(font)
        self.INC_line_INC.setFrame(False)
        self.euroteken_7 = QLabel(self.UpdateUser_page)
        self.euroteken_7.setObjectName(u"euroteken_7")
        self.euroteken_7.setGeometry(QRect(510, 712, 20, 40))
        self.euroteken_7.setFont(font)
        self.euroteken_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.INC_line_AMOUNT_2 = QLabel(self.UpdateUser_page)
        self.INC_line_AMOUNT_2.setObjectName(u"INC_line_AMOUNT_2")
        self.INC_line_AMOUNT_2.setGeometry(QRect(530, 712, 480, 40))
        self.INC_line_AMOUNT_2.setFont(font)
        self.INC_lbl_AMOUNT_2 = QLabel(self.UpdateUser_page)
        self.INC_lbl_AMOUNT_2.setObjectName(u"INC_lbl_AMOUNT_2")
        self.INC_lbl_AMOUNT_2.setGeometry(QRect(250, 712, 250, 40))
        self.INC_lbl_AMOUNT_2.setFont(font)
        self.btn_INC = QPushButton(self.UpdateUser_page)
        self.btn_INC.setObjectName(u"btn_INC")
        self.btn_INC.setGeometry(QRect(840, 875, 420, 175))
        self.btn_INC.setFont(font)
        self.btn_INC.setFocusPolicy(Qt.NoFocus)
        self.btn_INC.setCheckable(False)
        self.btn_INC.setChecked(False)
        self.btn_INC.setAutoExclusive(False)
        self.Users.addWidget(self.UpdateUser_page)
        self.EditUser_page = QWidget()
        self.EditUser_page.setObjectName(u"EditUser_page")
        self.line_ID = QLineEdit(self.EditUser_page)
        self.line_ID.setObjectName(u"line_ID")
        self.line_ID.setGeometry(QRect(550, 75, 500, 40))
        self.line_ID.setFont(font)
        self.line_ID.setFrame(False)
        self.lbl_ID = QLabel(self.EditUser_page)
        self.lbl_ID.setObjectName(u"lbl_ID")
        self.lbl_ID.setGeometry(QRect(185, 75, 215, 40))
        self.lbl_ID.setFont(font)
        self.lbl_NAME = QLabel(self.EditUser_page)
        self.lbl_NAME.setObjectName(u"lbl_NAME")
        self.lbl_NAME.setGeometry(QRect(185, 190, 215, 40))
        self.lbl_NAME.setFont(font)
        self.lbl_TITLE = QLabel(self.EditUser_page)
        self.lbl_TITLE.setObjectName(u"lbl_TITLE")
        self.lbl_TITLE.setGeometry(QRect(185, 305, 215, 40))
        self.lbl_TITLE.setFont(font)
        self.lbl_AMOUNT = QLabel(self.EditUser_page)
        self.lbl_AMOUNT.setObjectName(u"lbl_AMOUNT")
        self.lbl_AMOUNT.setGeometry(QRect(185, 420, 215, 40))
        self.lbl_AMOUNT.setFont(font)
        self.lbl_PASSWORD = QLabel(self.EditUser_page)
        self.lbl_PASSWORD.setObjectName(u"lbl_PASSWORD")
        self.lbl_PASSWORD.setGeometry(QRect(185, 535, 215, 40))
        self.lbl_PASSWORD.setFont(font)
        self.lbl_BLOCK = QLabel(self.EditUser_page)
        self.lbl_BLOCK.setObjectName(u"lbl_BLOCK")
        self.lbl_BLOCK.setGeometry(QRect(185, 650, 215, 40))
        self.lbl_BLOCK.setFont(font)
        self.lbl_QR = QLabel(self.EditUser_page)
        self.lbl_QR.setObjectName(u"lbl_QR")
        self.lbl_QR.setGeometry(QRect(185, 765, 215, 40))
        self.lbl_QR.setFont(font)
        self.btn_EDIT = QPushButton(self.EditUser_page)
        self.btn_EDIT.setObjectName(u"btn_EDIT")
        self.btn_EDIT.setGeometry(QRect(840, 875, 420, 175))
        self.btn_EDIT.setFont(font)
        self.btn_EDIT.setFocusPolicy(Qt.NoFocus)
        self.btn_EDIT.setCheckable(False)
        self.btn_EDIT.setChecked(False)
        self.btn_EDIT.setAutoExclusive(False)
        self.line_NAME = QLineEdit(self.EditUser_page)
        self.line_NAME.setObjectName(u"line_NAME")
        self.line_NAME.setGeometry(QRect(550, 200, 500, 40))
        self.line_NAME.setFont(font)
        self.line_NAME.setFrame(False)
        self.line_TITLE = QComboBox(self.EditUser_page)
        self.line_TITLE.addItem("")
        self.line_TITLE.addItem("")
        self.line_TITLE.addItem("")
        self.line_TITLE.setObjectName(u"line_TITLE")
        self.line_TITLE.setGeometry(QRect(550, 305, 500, 40))
        self.line_TITLE.setFont(font)
        self.line_TITLE.setFrame(False)
        self.line_PASSWORD = QLineEdit(self.EditUser_page)
        self.line_PASSWORD.setObjectName(u"line_PASSWORD")
        self.line_PASSWORD.setGeometry(QRect(550, 535, 500, 40))
        self.line_PASSWORD.setFont(font)
        self.line_PASSWORD.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.line_PASSWORD.setFrame(False)
        self.line_PASSWORD.setEchoMode(QLineEdit.Password)
        self.line_BLOCK = QCheckBox(self.EditUser_page)
        self.line_BLOCK.setObjectName(u"line_BLOCK")
        self.line_BLOCK.setGeometry(QRect(550, 650, 500, 40))
        self.line_BLOCK.setFont(font5)
        self.line_QR = QLineEdit(self.EditUser_page)
        self.line_QR.setObjectName(u"line_QR")
        self.line_QR.setGeometry(QRect(550, 765, 500, 40))
        self.line_QR.setFont(font)
        self.line_QR.setFrame(False)
        self.line_AMOUNT = QLineEdit(self.EditUser_page)
        self.line_AMOUNT.setObjectName(u"line_AMOUNT")
        self.line_AMOUNT.setGeometry(QRect(570, 420, 480, 40))
        self.line_AMOUNT.setFont(font)
        self.line_AMOUNT.setFrame(False)
        self.euroteken_5 = QLabel(self.EditUser_page)
        self.euroteken_5.setObjectName(u"euroteken_5")
        self.euroteken_5.setGeometry(QRect(550, 420, 20, 40))
        self.euroteken_5.setFont(font)
        self.euroteken_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.ERROR_UPDUSR = QLabel(self.EditUser_page)
        self.ERROR_UPDUSR.setObjectName(u"ERROR_UPDUSR")
        self.ERROR_UPDUSR.setGeometry(QRect(157, 930, 525, 60))
        self.ERROR_UPDUSR.setFont(font)
        self.Users.addWidget(self.EditUser_page)
        self.pages.addWidget(self.user_page)
        self.dev_line = QFrame(self.main)
        self.dev_line.setObjectName(u"dev_line")
        self.dev_line.setGeometry(QRect(420, 0, 2, 1080))
        font6 = QFont()
        font6.setPointSize(59)
        self.dev_line.setFont(font6)
        self.dev_line.setFrameShadow(QFrame.Plain)
        self.dev_line.setLineWidth(13)
        self.dev_line.setMidLineWidth(0)
        self.dev_line.setFrameShape(QFrame.VLine)
        self.stackedWidget.addWidget(self.main)
        self.retPSWRD = QWidget()
        self.retPSWRD.setObjectName(u"retPSWRD")
        self.retsteps = QStackedWidget(self.retPSWRD)
        self.retsteps.setObjectName(u"retsteps")
        self.retsteps.setGeometry(QRect(0, 0, 1680, 1050))
        self.verify = QWidget()
        self.verify.setObjectName(u"verify")
        self.txt_steps = QTextBrowser(self.verify)
        self.txt_steps.setObjectName(u"txt_steps")
        self.txt_steps.setGeometry(QRect(150, 160, 840, 130))
        self.txt_steps.setFont(font)
        self.txt_steps.setFrameShape(QFrame.NoFrame)
        self.txt_steps.setFrameShadow(QFrame.Plain)
        self.txt_steps.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_steps.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_steps.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.txt_steps.setTextInteractionFlags(Qt.NoTextInteraction)
        self.lbl_title = QLabel(self.verify)
        self.lbl_title.setObjectName(u"lbl_title")
        self.lbl_title.setGeometry(QRect(150, 40, 840, 120))
        self.lbl_title.setFont(font2)
        self.line_qr_ret = QLineEdit(self.verify)
        self.line_qr_ret.setObjectName(u"line_qr_ret")
        self.line_qr_ret.setGeometry(QRect(2000, 600, 840, 120))
        sizePolicy1.setHeightForWidth(self.line_qr_ret.sizePolicy().hasHeightForWidth())
        self.line_qr_ret.setSizePolicy(sizePolicy1)
        self.line_qr_ret.setFont(font2)
        self.line_qr_ret.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhPreferNumbers|Qt.ImhSensitiveData)
        self.line_qr_ret.setFrame(False)
        self.line_qr_ret.setEchoMode(QLineEdit.Normal)
        self.line_qr_ret.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.line_stdnr_ret = QLineEdit(self.verify)
        self.line_stdnr_ret.setObjectName(u"line_stdnr_ret")
        self.line_stdnr_ret.setGeometry(QRect(150, 480, 840, 120))
        sizePolicy1.setHeightForWidth(self.line_stdnr_ret.sizePolicy().hasHeightForWidth())
        self.line_stdnr_ret.setSizePolicy(sizePolicy1)
        self.line_stdnr_ret.setFont(font2)
        self.line_stdnr_ret.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhPreferNumbers|Qt.ImhSensitiveData)
        self.line_stdnr_ret.setFrame(False)
        self.line_stdnr_ret.setEchoMode(QLineEdit.Normal)
        self.line_stdnr_ret.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.ERROR_VERIFY = QLabel(self.verify)
        self.ERROR_VERIFY.setObjectName(u"ERROR_VERIFY")
        self.ERROR_VERIFY.setGeometry(QRect(150, 750, 840, 120))
        self.btn_next = QPushButton(self.verify)
        self.btn_next.setObjectName(u"btn_next")
        self.btn_next.setGeometry(QRect(1260, 875, 420, 175))
        self.btn_next.setFont(font)
        self.btn_next.setFocusPolicy(Qt.NoFocus)
        self.btn_next.setCheckable(False)
        self.btn_next.setChecked(False)
        self.btn_next.setAutoExclusive(False)
        self.retsteps.addWidget(self.verify)
        self.change = QWidget()
        self.change.setObjectName(u"change")
        self.line_pass_ret = QLineEdit(self.change)
        self.line_pass_ret.setObjectName(u"line_pass_ret")
        self.line_pass_ret.setGeometry(QRect(150, 480, 840, 120))
        sizePolicy1.setHeightForWidth(self.line_pass_ret.sizePolicy().hasHeightForWidth())
        self.line_pass_ret.setSizePolicy(sizePolicy1)
        self.line_pass_ret.setFont(font2)
        self.line_pass_ret.setInputMethodHints(Qt.ImhHiddenText|Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhSensitiveData)
        self.line_pass_ret.setFrame(False)
        self.line_pass_ret.setEchoMode(QLineEdit.Password)
        self.line_pass_ret.setCursorMoveStyle(Qt.VisualMoveStyle)
        self.txt_steps_2 = QTextBrowser(self.change)
        self.txt_steps_2.setObjectName(u"txt_steps_2")
        self.txt_steps_2.setGeometry(QRect(150, 160, 840, 120))
        self.txt_steps_2.setFont(font)
        self.txt_steps_2.setFrameShape(QFrame.NoFrame)
        self.txt_steps_2.setFrameShadow(QFrame.Plain)
        self.txt_steps_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_steps_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txt_steps_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.txt_steps_2.setTextInteractionFlags(Qt.NoTextInteraction)
        self.lbl_title_2 = QLabel(self.change)
        self.lbl_title_2.setObjectName(u"lbl_title_2")
        self.lbl_title_2.setGeometry(QRect(150, 40, 840, 120))
        self.lbl_title_2.setFont(font2)
        self.btn_save = QPushButton(self.change)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(1260, 875, 420, 175))
        self.btn_save.setFont(font)
        self.btn_save.setFocusPolicy(Qt.NoFocus)
        self.btn_save.setCheckable(False)
        self.btn_save.setChecked(False)
        self.btn_save.setAutoExclusive(False)
        self.ERROR_CHANGE = QLabel(self.change)
        self.ERROR_CHANGE.setObjectName(u"ERROR_CHANGE")
        self.ERROR_CHANGE.setGeometry(QRect(150, 750, 840, 120))
        self.ERROR_CHANGE.setWordWrap(True)
        self.retsteps.addWidget(self.change)
        self.stackedWidget.addWidget(self.retPSWRD)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)
        self.pages.setCurrentIndex(0)
        self.Users.setCurrentIndex(1)
        self.retsteps.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"KyberKiosk", None))
        self.btn_qr.setText("")
        self.btn_login.setText(QCoreApplication.translate("MainWindow", u"Log in", None))
        self.line_stdnr.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Studentnummer", None))
        self.line_pswrd.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Wachtwoord", None))
        self.ERROR_STDNR.setText("")
        self.ERROR_PSWRD.setText("")
        self.ERROR_QRFLD.setText("")
        self.btn_retpass.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord vergeten", None))
        self.buy_btn.setText(QCoreApplication.translate("MainWindow", u"Winkelwagen", None))
        self.stat_btn.setText(QCoreApplication.translate("MainWindow", u"Statistieken", None))
        self.prof_btn.setText(QCoreApplication.translate("MainWindow", u"Profiel", None))
        self.prod_btn.setText(QCoreApplication.translate("MainWindow", u"Producten", None))
        self.user_btn.setText(QCoreApplication.translate("MainWindow", u"Gebruikers", None))
#if QT_CONFIG(tooltip)
        self.logout_btn.setToolTip(QCoreApplication.translate("MainWindow", u"Als je vergeet uit te loggen, en een ander ziet dat, dan tracteer jij!", None))
#endif // QT_CONFIG(tooltip)
        self.logout_btn.setText(QCoreApplication.translate("MainWindow", u"Log uit!", None))
        self.pay_btn.setText(QCoreApplication.translate("MainWindow", u"Afrekenen", None))
        ___qtablewidgetitem = self.cart_fld.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem1 = self.cart_fld.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Item", None));
        ___qtablewidgetitem2 = self.cart_fld.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Qty", None));
        ___qtablewidgetitem3 = self.cart_fld.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Prijs", None));
        ___qtablewidgetitem4 = self.cart_fld.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Totaal", None));
        self.gebruiker_lbl.setText(QCoreApplication.translate("MainWindow", u"Gebruiker: ", None))
        self.teGoed_lbl.setText(QCoreApplication.translate("MainWindow", u"Tegoed: ", None))
        self.gebruiker_fld.setText("")
        self.euroteken.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.teGoed_fld.setText("")
        self.euroteken_2.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.totaal_lbl.setText(QCoreApplication.translate("MainWindow", u"Totaal:", None))
        self.totaal_fld.setText(QCoreApplication.translate("MainWindow", u"0.00", None))
        self.ERROR_ITMFLD.setText("")
        self.lbl_spend.setText(QCoreApplication.translate("MainWindow", u"Totaal uitgegeven:", None))
        self.lbl_bought.setText(QCoreApplication.translate("MainWindow", u"Totaal aantal items gekocht:", None))
        self.euroteken_8.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.fld_spend.setText("")
        self.fld_bought.setText("")
#if QT_CONFIG(tooltip)
        self.prof_page.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Lid: Je mag niet in de min staan</p><p>Commissie: Je mag 5 euro in de min staan</p><p>Bestuur: Je mag 10 euro in de min staan</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.line_BLOCK_prof.setText("")
        self.lbl_AMOUNT_prof.setText(QCoreApplication.translate("MainWindow", u"Tegoed", None))
        self.lbl_BLOCK_prof.setText(QCoreApplication.translate("MainWindow", u"Geblokeerd", None))
        self.euroteken_prof.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.ERROR_UPDUSR_prof.setText("")
        self.lbl_TITLE_prof.setText(QCoreApplication.translate("MainWindow", u"Rol", None))
        self.lbl_ID_prof.setText(QCoreApplication.translate("MainWindow", u"Studennummer", None))
        self.lbl_NAME_prof.setText(QCoreApplication.translate("MainWindow", u"Naam", None))
        self.lbl_PASSWORD_prof.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord", None))
        self.btn_EDIT_prof.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
        self.lbl_QR_prof.setText(QCoreApplication.translate("MainWindow", u"QR-code", None))
        self.EditProd_btn.setText(QCoreApplication.translate("MainWindow", u"Producten Wijzigen", None))
        self.NewProd_btn.setText(QCoreApplication.translate("MainWindow", u"Nieuw Product", None))
        ___qtablewidgetitem5 = self.ProdList.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem6 = self.ProdList.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Product", None));
        ___qtablewidgetitem7 = self.ProdList.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Prijs", None));
        ___qtablewidgetitem8 = self.ProdList.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Voorraad", None));
        ___qtablewidgetitem9 = self.ProdList.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Verkocht", None));
        ___qtablewidgetitem10 = self.ProdList.horizontalHeaderItem(5)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Datum", None));
        ___qtablewidgetitem11 = self.ProdList.horizontalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        self.UpdateUser_btn.setText(QCoreApplication.translate("MainWindow", u"Opwaarderen", None))
        self.EditUser_btn.setText(QCoreApplication.translate("MainWindow", u"Bewerken", None))
        self.NewUser_btn.setText(QCoreApplication.translate("MainWindow", u"Nieuw", None))
        self.lbl_ID_ADD.setText(QCoreApplication.translate("MainWindow", u"Studennummer", None))
        self.lbl_TITLE_ADD.setText(QCoreApplication.translate("MainWindow", u"Rol", None))
        self.lbl_BLOCK_ADD.setText(QCoreApplication.translate("MainWindow", u"Geblokeerd", None))
        self.lbl_QR_ADD.setText(QCoreApplication.translate("MainWindow", u"QR-code", None))
        self.line_TITLE_ADD.setItemText(0, QCoreApplication.translate("MainWindow", u"Lid", None))
        self.line_TITLE_ADD.setItemText(1, QCoreApplication.translate("MainWindow", u"Commissie", None))
        self.line_TITLE_ADD.setItemText(2, QCoreApplication.translate("MainWindow", u"Bestuur", None))

        self.lbl_PASSWORD_ADD.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord", None))
        self.btn_ADD.setText(QCoreApplication.translate("MainWindow", u"Toevoegen", None))
        self.lbl_NAME_ADD.setText(QCoreApplication.translate("MainWindow", u"Naam", None))
        self.lbl_AMOUNT_ADD.setText(QCoreApplication.translate("MainWindow", u"Tegoed", None))
        self.line_BLOCK_ADD.setText("")
        self.euroteken_4.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.ERROR_ADDUSR.setText("")
        self.INC_lbl_ID.setText(QCoreApplication.translate("MainWindow", u"Studentnummer", None))
        self.INC_lbl_AMOUNT.setText(QCoreApplication.translate("MainWindow", u"Huidig saldo", None))
        self.INC_line_AMOUNT.setText("")
        self.euroteken_3.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.euroteken_6.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.INC_lbl_INC.setText(QCoreApplication.translate("MainWindow", u"Opwaardeer saldo", None))
        self.euroteken_7.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.INC_line_AMOUNT_2.setText("")
        self.INC_lbl_AMOUNT_2.setText(QCoreApplication.translate("MainWindow", u"Nieuw Saldo", None))
        self.btn_INC.setText(QCoreApplication.translate("MainWindow", u"Opwaarderen", None))
        self.lbl_ID.setText(QCoreApplication.translate("MainWindow", u"Studennummer", None))
        self.lbl_NAME.setText(QCoreApplication.translate("MainWindow", u"Naam", None))
        self.lbl_TITLE.setText(QCoreApplication.translate("MainWindow", u"Rol", None))
        self.lbl_AMOUNT.setText(QCoreApplication.translate("MainWindow", u"Tegoed", None))
        self.lbl_PASSWORD.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord", None))
        self.lbl_BLOCK.setText(QCoreApplication.translate("MainWindow", u"Geblokeerd", None))
        self.lbl_QR.setText(QCoreApplication.translate("MainWindow", u"QR-code", None))
        self.btn_EDIT.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
        self.line_TITLE.setItemText(0, QCoreApplication.translate("MainWindow", u"Lid", None))
        self.line_TITLE.setItemText(1, QCoreApplication.translate("MainWindow", u"Commissie", None))
        self.line_TITLE.setItemText(2, QCoreApplication.translate("MainWindow", u"Bestuur", None))

        self.line_BLOCK.setText("")
        self.euroteken_5.setText(QCoreApplication.translate("MainWindow", u"\u20ac", None))
        self.ERROR_UPDUSR.setText("")
        self.txt_steps.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">stap 1: Vul hieronder je studentnummer in,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            en klik op volgende (enter werkt ook) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">stap 2: Scan je log in qr code</p></body></html>", None))
        self.lbl_title.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord wijzigen", None))
        self.line_qr_ret.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Studentnummer", None))
        self.line_stdnr_ret.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Studentnummer", None))
        self.ERROR_VERIFY.setText("")
        self.btn_next.setText(QCoreApplication.translate("MainWindow", u"Volgende", None))
        self.line_pass_ret.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nieuw Wachtwoord", None))
        self.txt_steps_2.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Je ingevulde gegevens zijn correct,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nu kan jij je nieuwe wachtwoord invullen, en op opslaan klikken.</p></body></html>", None))
        self.lbl_title_2.setText(QCoreApplication.translate("MainWindow", u"Wachtwoord wijzigen", None))
        self.btn_save.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
        self.ERROR_CHANGE.setText("")
    # retranslateUi

